---
# ansible/roles/terminator/tasks/main.yml

- name: Create a symbolic link 
  file:
    src: "{{ playbook_dir }}/roles/terminator/files/terminator"
    dest: "/home/{{ username }}/.config/terminator"
    state: link
    force: yes

