---
# ansible/roles/vim/tasks/main.yml

- name: Create a symbolic link
  file:
    src: "{{ playbook_dir }}/roles/xkb/files/00-keyboard.conf"
    dest: "/usr/share/X11/xorg.conf.d/00-keyboard.conf"
    state: link
    force: yes

