# ansible/roles/packages/tasks/main.yml

---

# FreeBSD-specific tasks
- name: FreeBSD-specific tasks
  ansible.builtin.pkgng:
    name: '{{ packages_to_install }}'
    state: present
  when: ansible_facts['distribution'] == 'FreeBSD'
  ignore_errors: yes

# Fedora-specific tasks
- name: Fedora-specific tasks
  ansible.builtin.dnf:
    name: '{{ packages_to_install }}'
    state: present
  when: ansible_facts['distribution'] == 'Fedora'
  ignore_errors: yes

# Debian-based-specific tasks
- name: Debian-based-specific tasks
  ansible.builtin.apt:
    include_tasks: debian.yml
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  ignore_errors: yes

# Github cloning tasks
- name: Github cloning tasks
  include_tasks: cloning.yml
  ignore_errors: yes
