---
# ansible/roles/packages/tasks/main.yml

- name: Update the DNF package manager cache
  dnf:
    update_cache: yes

- name: Install the required packages using DNF
  dnf:
    name: "{{ f_packages }}"
    state: present

