---
# ansible/roles/i3/tasks/main.yml

- name: Create a symbolic link 
  file:
    src: "{{ playbook_dir }}/../config_files/i3/"
    dest: "/home/{{ username }}/.config/i3/"
    state: link
    force: yes

