---
# ansible/roles/vim/tasks/main.yml

- name: Create a symbolic link 
  file:
    src: "{{ playbook_dir }}/roles/vim/files/.vimrc"
    dest: "/home/{{ username }}/.vimrc"
    state: link
    force: yes

