---
- name: Configure my system
  hosts: localhost
  become: true
  vars:
     packages_to_install:
       - curl
       - zsh
       - bat
       - python3
       - git
       - tldr
       - terminator
       - tmux
       - polybar
       - picom
       - fira-code-fonts
       - xrandr
       - nitrogen
       - maim
       - i3
  roles:
   - packages
   - zsh
   - vim
   - polybar
   - i3
   - picom
   - terminator
   - xkb
   - autorandr
