---
# ansible/roles/picom/tasks/main.yml

- name: Create a symbolic link 
  file:
    src: "{{ playbook_dir }}/roles/picom/files/picom"
    dest: "/home/{{ username }}/.config/picom"
    state: link
    force: yes

