---
# ansible/roles/picom/tasks/main.yml

- name: Check if the picom directory exists
  stat:
    path: "/home/{{ username }}/.config/picom"
  register: folder_check

- name: Delete the existing /home/{{ username }}/.config/picom if it exists
  file:
    path: "/home/{{ username }}/.config/picom"
    state: absent
  when: folder_check.stat.exists

- name: Create a symbolic link 
  file:
    src: "{{ playbook_dir }}/roles/picom/files/picom"
    dest: "/home/{{ username }}/.config/picom"
    state: link
    force: yes

